{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.castify",
    "module": "castify-sdk",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "castify-sdk-2.0.0.aar",
          "url": "castify-sdk-2.0.0.aar",
          "size": 10562705,
          "sha512": "f8c21fc868150945881bbc0b62e075cb481950421d50c9052dc392e76d2215dd15f6efe1fc598dd68851de0bfdebd1d5a45db225cc9d1565d6c36e84efbcad65",
          "sha256": "688b77d3ea16f5b75eda5f2dc25f3ea1d13df427f3e19fcce9439c84d56b2723",
          "sha1": "ee20a1aff453d818442da5fb906969800af2a201",
          "md5": "d51c0515177ca079d25990916f450d13"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "castify-sdk-2.0.0.aar",
          "url": "castify-sdk-2.0.0.aar",
          "size": 10562705,
          "sha512": "f8c21fc868150945881bbc0b62e075cb481950421d50c9052dc392e76d2215dd15f6efe1fc598dd68851de0bfdebd1d5a45db225cc9d1565d6c36e84efbcad65",
          "sha256": "688b77d3ea16f5b75eda5f2dc25f3ea1d13df427f3e19fcce9439c84d56b2723",
          "sha1": "ee20a1aff453d818442da5fb906969800af2a201",
          "md5": "d51c0515177ca079d25990916f450d13"
        }
      ]
    }
  ]
}
