{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.castify",
    "module": "castify-sdk",
    "version": "1.0.0-RC.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "dv24m7uryzaq7bdw6sezvpah6m"
    }
  },
  "variants": [
    {
      "name": "strippedReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "castify-sdk-1.0.0-RC.1.aar",
          "url": "castify-sdk-1.0.0-RC.1.aar",
          "size": 17330312,
          "sha512": "17dd0b741ef4efa305483f07ff784bd9520b868c3b56645890eb077c8573e0b823f68528971d1f16c7c174725b6f6c0ee6af8f9d56bc7a452c940c1829ff7542",
          "sha256": "27829ef9b0482dfbb25a0abbd710228bfdd1dab5238e10e6e802c28462b73c90",
          "sha1": "347a85a43659d8ca640c45b8d12f9be2ff3fadc9",
          "md5": "0ad993e20d65f5495906d4330f73edf8"
        }
      ]
    },
    {
      "name": "strippedReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "castify-sdk-1.0.0-RC.1.aar",
          "url": "castify-sdk-1.0.0-RC.1.aar",
          "size": 17330312,
          "sha512": "17dd0b741ef4efa305483f07ff784bd9520b868c3b56645890eb077c8573e0b823f68528971d1f16c7c174725b6f6c0ee6af8f9d56bc7a452c940c1829ff7542",
          "sha256": "27829ef9b0482dfbb25a0abbd710228bfdd1dab5238e10e6e802c28462b73c90",
          "sha1": "347a85a43659d8ca640c45b8d12f9be2ff3fadc9",
          "md5": "0ad993e20d65f5495906d4330f73edf8"
        }
      ]
    }
  ]
}
