{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.castify",
    "module": "castify-sdk",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "pwwisyeip5divesk5o7l3vjczi"
    }
  },
  "variants": [
    {
      "name": "strippedReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "castify-sdk-1.0.0.aar",
          "url": "castify-sdk-1.0.0.aar",
          "size": 17151242,
          "sha512": "d0706f532db1487fb3922db1e326f4acb2dcb228e5e3305709360fe2405d2d4d7ee02e3abc95f96a903c01b3b395b1e5176f77850a46214cdf2c861e63c0870b",
          "sha256": "53762292ecf028787f0a14426544e7a4300d118525aa31f97322f65178318c16",
          "sha1": "3ae2e3215ff4cba8e1bf8ade46fabaf0b9f2cecf",
          "md5": "d884dc786e165286d0296cfc4c46f6fd"
        }
      ]
    },
    {
      "name": "strippedReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "castify-sdk-1.0.0.aar",
          "url": "castify-sdk-1.0.0.aar",
          "size": 17151242,
          "sha512": "d0706f532db1487fb3922db1e326f4acb2dcb228e5e3305709360fe2405d2d4d7ee02e3abc95f96a903c01b3b395b1e5176f77850a46214cdf2c861e63c0870b",
          "sha256": "53762292ecf028787f0a14426544e7a4300d118525aa31f97322f65178318c16",
          "sha1": "3ae2e3215ff4cba8e1bf8ade46fabaf0b9f2cecf",
          "md5": "d884dc786e165286d0296cfc4c46f6fd"
        }
      ]
    }
  ]
}
